
Traceback (most recent call last):
  File "/workspaces/sphinxcontrib-skeleton/.nox/docs/lib/python3.11/site-packages/sphinx/registry.py", line 447, in load_extension
    mod = import_module(extname)
          ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1140, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'sphinxcontrib.skeleton'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/workspaces/sphinxcontrib-skeleton/.nox/docs/lib/python3.11/site-packages/sphinx/cmd/build.py", line 293, in build_main
    app = Sphinx(args.sourcedir, args.confdir, args.outputdir,
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspaces/sphinxcontrib-skeleton/.nox/docs/lib/python3.11/site-packages/sphinx/application.py", line 233, in __init__
    self.setup_extension(extension)
  File "/workspaces/sphinxcontrib-skeleton/.nox/docs/lib/python3.11/site-packages/sphinx/application.py", line 406, in setup_extension
    self.registry.load_extension(self, extname)
  File "/workspaces/sphinxcontrib-skeleton/.nox/docs/lib/python3.11/site-packages/sphinx/registry.py", line 450, in load_extension
    raise ExtensionError(__('Could not import extension %s') % extname,
sphinx.errors.ExtensionError: Could not import extension sphinxcontrib.skeleton (exception: No module named 'sphinxcontrib.skeleton')

[91mExtension error:[39;49;00m
Could not import extension sphinxcontrib.skeleton (exception: No module named 'sphinxcontrib.skeleton')
